name: custom-set

dependencies:
  - base

library:
  exposed-modules: CustomSet
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - custom-set
      - hspec
