name: parallel-letter-frequency

# -threaded -eventlog -rtsopts -O2
ghc-options: -threaded -eventlog -rtsopts -O2

dependencies:
  - base
  - containers
  - text
  - parallel
  - split
  - criterion

library:
  exposed-modules: Frequency
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - parallel-letter-frequency
      - statistics
      - hspec

benchmarks:
  bench:
    main: Benchmark.hs
    source-dirs: bench
    dependencies:
      - parallel-letter-frequency
      - criterion
